;;; -*- Mode: Lisp; Package: ZWEI -*-
;;; ** (c) Copyright 1980 Massachusetts Institute of Technology **
;;; This is the last file loaded in the editor, it should contain only flavors
;;; and initializations

;;; Compile the necessary flavors

(COMPILE-FLAVOR-METHODS EDITOR-TYPEOUT-WINDOW ZWEI-WITH-TYPEOUT
			ECHO-AREA-WINDOW TYPEIN-WINDOW
			EDITOR TOP-LEVEL-EDITOR ZMACS-EDITOR ZMACS-TOP-LEVEL-EDITOR
			ZWEI-WINDOW ZWEI-WINDOW-PANE ZMACS-WINDOW ZMACS-WINDOW-PANE
			MODE-LINE-WINDOW ZMACS-MODE-LINE-WINDOW
			ZWEI-FRAME ZMACS-FRAME MENU-COMMAND-MOMENTARY-MENU
			EDITOR-STREAM-WINDOW EDITOR-TOP-LEVEL
			ZWEI-WITH-TYPEOUT-UNSELECTABLE ZWEI-MINI-BUFFER
			STANDALONE-EDITOR-WINDOW STANDALONE-EDITOR-PANE
			MAIL-TOP-LEVEL-EDITOR SOURCE-COMPARE-MERGE-TOP-LEVEL-EDITOR
			ZTOP-STREAM-FROM-WINDOW
			TEMPORARY-MODE-LINE-WINDOW TEMPORARY-MODE-LINE-WINDOW-WITH-BORDERS
			EDITOR-FOR-TEMPORARY-MINI-BUFFER
			EDITOR-STREAM-FROM-WINDOW STREAM-IBEAM-BLINKER
			BACKGROUND-TYPEOUT-WINDOW)

(DEFVAR *EDITOR-INITIALIZATION-LIST*)

;;;Initialize the editor the first time we are loaded up
(DEFUN INITIALIZE-ALL-OF-EDITOR (&AUX (PACKAGE PACKAGE))
  (LET ((ELEM (ASSOC "INITIALIZE-ZMACS-IF-NECESSARY" *EDITOR-INITIALIZATION-LIST*)))
    (AND ELEM (SETQ *EDITOR-INITIALIZATION-LIST*
		    (CONS ELEM (DELQ ELEM *EDITOR-INITIALIZATION-LIST*)))))
  (TV:WITHOUT-SCREEN-MANAGEMENT
    (INITIALIZATIONS '*EDITOR-INITIALIZATION-LIST*))
  (USING-RESOURCE (EDITOR EDITOR-FOR-TEMPORARY-MINI-BUFFER-RESOURCE))	;Make one
  (USING-RESOURCE (WINDOW BACKGROUND-TYPEOUT-WINDOWS))
  )

(ADD-INITIALIZATION "INITIALIZE-ALL-OF-EDITOR"
		    '(INITIALIZE-ALL-OF-EDITOR)
		    '(:ONCE))
