;;; -*- Mode: LISP; Package: CHAOS; Base: 8 -*-
;;; *** THIS FILE WAS AUTOMATICALLY GENERATED BY A PROGRAM, DO NOT EDIT IT ***
;;; Host table made from server: /home/ams/mit-cadr/lisp/chaos/hosts.text by AMS at 10/09/00 10:23:45
(SI:DEFINE-HOST "SERVER"
                ':HOST-NAMES
                '("SERVER")
                ':MACHINE-TYPE
                ':VAX
                ':SYSTEM-TYPE
                ':UNIX
                ':CHAOS
                '(404))
(SI:DEFINE-HOST "CADR"
                ':HOST-NAMES
                '("CADR")
                ':MACHINE-TYPE
                ':LISPM
                ':SYSTEM-TYPE
                ':LISPM
                ':CHAOS
                '(401))
