;;; -*- Mode: LISP; Package: CHAOS; Base: 8 -*-
;;; *** THIS FILE WAS AUTOMATICALLY GENERATED BY A PROGRAM, DO NOT EDIT IT ***
;;; Host table made from SERVER: /tree/chaos/HOSTS.TEXT by brad at 1/01/70 10:15:21
(SI:DEFINE-HOST "SERVER"
                ':HOST-NAMES
                '("SERVER")
                ':MACHINE-TYPE
                ':VAX
                ':SYSTEM-TYPE
                ':UNIX
                ':CHAOS
                '(404))
(SI:DEFINE-HOST "CADR"
                ':HOST-NAMES
                '("CADR")
                ':MACHINE-TYPE
                ':LISPM
                ':SYSTEM-TYPE
                ':LISPM
                ':CHAOS
                '(401))
