;;; Lisp Machine mail reader -*- Mode:LISP; Package:ZWEI -*- 
;;; Compiled flavor methods and initializations only
;;; ** (c) Copyright 1980 Massachusetts Institute of Technology **

(COMPILE-FLAVOR-METHODS CLICK-REMEMBERING-POP-UP-MENU FILTER-SELECTION-FRAME MODE-LINE-PANE
			POP-UP-STANDALONE-EDITOR-FRAME POP-UP-ZMAIL-MULTIPLE-MENU
			UNIVERSE-DEFINITION-FRAME ZMAIL-COMMAND-MENU-PANE
			ZMAIL-DYNAMIC-MOMENTARY-COMMAND-MENU ZMAIL-FILTER-FRAME ZMAIL-FRAME
			ZMAIL-MAIN-COMMAND-MENU-PANE ZMAIL-MOMENTARY-COMMAND-MENU
			ZMAIL-MOMENTARY-MENU ZMAIL-MOUSE-SENSITIVE-MODE-LINE-PANE
			ZMAIL-OVERLYING-WINDOW ZMAIL-PROFILE-FRAME ZMAIL-SUMMARY-SCROLL-WINDOW
			ZMAIL-SUMMARY-TYPEOUT-WINDOW ZMAIL-TYPEOUT-WINDOW ZMAIL-WINDOW
			ZMAIL-CHOOSE-VARIABLE-VALUES-PANE ZMAIL-COMMAND-MENU-PANE
			ZMAIL-PROFILE-EDITOR)

(COMPILE-FLAVOR-METHODS ITS-MAIL-FILE ITS-NEW-MAIL-FILE BABYL-MAIL-FILE RMAIL-MAIL-FILE
			TENEX-MAIL-FILE TENEX-OLD-MAIL-FILE TEXT-MAIL-FILE)

(DEFWINDOW-RESOURCE ZMAIL-MOMENTARY-MENU ()
  :MAKE-WINDOW (ZMAIL-MOMENTARY-MENU)
  :REUSABLE-WHEN :DEEXPOSED)

(DEFWINDOW-RESOURCE ZMAIL-MOMENTARY-COMMAND-MENU ()
  :MAKE-WINDOW (ZMAIL-MOMENTARY-COMMAND-MENU)
  :REUSABLE-WHEN :DEEXPOSED)

(DEFWINDOW-RESOURCE POP-UP-ZMAIL-MULTIPLE-MENU ()
  :MAKE-WINDOW (POP-UP-ZMAIL-MULTIPLE-MENU)
  :REUSABLE-WHEN :DEEXPOSED)

(DEFWINDOW-RESOURCE POP-UP-STANDALONE-EDITOR-FRAME ()
  :MAKE-WINDOW (POP-UP-STANDALONE-EDITOR-FRAME)
  :REUSABLE-WHEN :DEACTIVATED)

(ADD-INITIALIZATION "INITIALIZE-ZMAIL" '(INITIALIZE-ZMAIL) '(:ONCE))
